spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080
